## This file contains sensitive properties of the EBX application keystore.
## Access to this file should be restricted to the operating system user that is running EBX.
##
## The keystore type.
ebx.keystore.type=PKCS12
##
## The keystore path.
## If relative, it's absolute path is resolved against this file's folder.
## This property should be removed if the keystore type is not file based.
ebx.keystore.path=ebx-keystore.p12
##
## The keystore password.
ebx.keystore.password.obf=vakwmKky/IfeYoOGjBbZ2kO+kajtC2np9otGl9r5Kh2Ub8qrSh7ZZTpZGRoi+8MwY7sIw6s7pS+v8w==
##
## The alias of the secret key used to encrypt password type values.
ebx.keystore.key.passwordType.alias=ebx.passwordType
##
## The password of the secret key used to encrypt password type values.
## For PKCS12 keystores, should be the same as the keystore password.
ebx.keystore.key.passwordType.password.obf=vakwmKky/IfeYoOGjBbZ2kO+kajtC2np9otGl9r5Kh2Ub8qrSh7ZZTpZGRoi+8MwY7sIw6s7pS+v8w==
##
## The alias of the secret key used to sign web tokens.
ebx.keystore.key.webToken.alias=ebx.webToken
##
## The password of the secret key used to sign web tokens.
## For PKCS12 keystores, should be the same as the keystore password.
ebx.keystore.key.webToken.password.obf=vakwmKky/IfeYoOGjBbZ2kO+kajtC2np9otGl9r5Kh2Ub8qrSh7ZZTpZGRoi+8MwY7sIw6s7pS+v8w==
