#-------------------------------------------------------------
# Messaging setup
#-------------------------------------------------------------
#
# Indicates if he messaging framework is being used. false - will prevent from the system to be loaded.
#
ebx.messaging.enable=true

#
# The messaging framework support multiple servers. to enable the feature the logical server names must be listed in a comma delimited string 
# with this property. for each logical server there needs to be a set of properties with the logical name as a prefix. 
# For example: ebx.messaging.servers=tibco, rabbit
# to specify to url for tibco the property name needs to be "tibco.ebx.messaging.host" for the port "tibco.ebx.messaging.port" etc.
#
#
ebx.messaging.servers=
#
# Configuration class name - a class that extends the class "com.orchestranetworks.ps.messaging.PublishSubscribeConfiguration"
# com.orchestranetworks.ps.messaging.PropertiesFilePublishSubscribeConfiguration is provided with the framework and uses a property file for configuration
# the properties can be specified in ebx.properties or in it's own file. 
#
ebx.messaging.configurationClassName=com.orchestranetworks.ps.messaging.PropertiesFilePublishSubscribeConfiguration

#
# ebx.messaging.clientclassname - messaging client to use with the framework. examples: 
# 		com.orchestranetworks.ps.messaging.client.rabbitmq.RabbitMQClient, 
# 		com.orchestranetworks.ps.messaging.client.tibco.TibcoEmsClient, 
# 		com.orchestranetworks.ps.messaging.client.kafka.KafkaClient
#		com.orchestranetworks.ps.messaging.jndi.JNDIMessagingClient
#

ebx.messaging.clientclassname=com.orchestranetworks.ps.messaging.client.rabbitmq.RabbitMQClient
#################################################################################################
#
# Depending on the method to connect to the messaging technology, we need to specify either properties for direct connection
# or properties for connecting via JNDI
#
#################################################################################################
#################################################################################################
#
# properties that are relevant when connecting directly to the messaging technology.
#
#################################################################################################
#
# ebx.messaging.host - host name of the messaging server.
#
ebx.messaging.host=localhost
#
# ebx.messaging.port - port number of the messaging server.
#
ebx.messaging.port=5672

#################################################################################################
#
# properties that are relevant when connecting via JNDI to the messaging technology.
#
#################################################################################################
# if using jms jndi, to specify the connection factory jndi name
# with tomcat the ConnectionFactory name needs to be configured in tomact context.xml. and the Connection Factory name needs to be prefixed with "java:/comp/env/". 
# for example if your connection factory name is "jms/ConnectionFactory" then the value need to be "java:/comp/env/jms/ConnectionFactory"
ebx.messaging.connection.jndifactoryname=java:/comp/env/jms/ConnectionFactory

#################################################################################################
#
# properties that are needed regardless of how we connect to the messaging technology.
#
#################################################################################################
#
# ebx.messaging.username - user name to connect to the messaging server.
#
ebx.messaging.username=guest
#
# ebx.messaging.passwword - password to connect to the messaging server.
#
ebx.messaging.password=guest

# default destination name for inbound messages. this can be either a topic name or a queue name. when calling the method to "sending" the messages depending on the method one of the 
# 2 options will be used. subscribe - topic, readMessages - queue.
# with tomcat those destination needs to be configured in tomact context.xml. and the destination name needs to be prefixed with "java:/comp/env/". for exmaple if your topic name is "jms/inbound" 
# then the value need to be "java:/comp/env/jms/inbound"
ebx.messaging.inbound.destinationname=java:/comp/env/inbound

# set the output format for the default transformation class. nicely formatted or just a long string 
ebx.messaging.outbound.useprettyprint=true

# default destination name for outbound messages. this can be either a topic name or a queue name. when calling the method to "sendread" the messages depending on the method one of the 
# 2 options will be used. publishMessage - topic, sendMessage - queue.
ebx.messaging.outbound.destinationname=java:/comp/env/outbound

# timeout - the time to wait when reading messages from a queue or topic. if this time pass it will be considered as no messages received 
ebx.messaging.connection.timeout=6000

# reuse a connection. it is strongly recommended with RabbitMQ to reuse the connection for bettr performance.
# kafka on the other end don't have a concept of a connection in the client side.
ebx.messaging.connection.reuse=true


