##################################################################
## EBX® License Key
##    Ensure the file is writable by EBX®
##    to enable updates using the UI license key wizard process.
##################################################################
ebx.license=
#expires-2026-06-29
