##################################################################
## EBX® License Key
##    Ensure the file is writable by EBX®
##    to enable updates using the UI license key wizard process.
##################################################################
ebx.license=TIVPR-1582N-E5DRE-PX0Z8
#expires-2026-06-29
