##artifactsFolder =       ../ebx-parent/company-mdm/artifacts

artifactsFolder = ../ebx-parent/onebx-mdm/src/main/webapp/artifacts

##copyEnvironmentFolder = ../ebx-parent/company-mdm/WebContent/copyEnv
copyEnvironmentFolder = ../ebx-parent/onebx-mdm/src/main/webapp/copyEnv


# windows (\r\n) or unix (\n)
lineSeparator = windows

#Define dev artifacts service behavior
# single (default), multi, multi-admin
tenantPolicy = single

# The modules this tenant includes (ignored for single)
modules = onebx-mdm

# Whether to enable downloading to local file system
enableDownloadToLocal = false

# Default options
defaultEnvironmentCopy = true
defaultPublishWorkflowModels = true
defaultReplaceMode = true
defaultSkipNonExistingFiles = false
defaultDownloadToLocal = false
refreshSchemas = true

#Dataspace | Dataset | Table Path (or * for all)
#tablesForData = \
#		Dataspace|Dataset|*

#Create specified dataspaces if they don't exist
createDataSpaces = true

#Dataspace | Parent Dataspace | Label | Owner
#Only Dataspace need be specified if createDataSpaces is false
#If Parent blank, assumes Reference (except Reference itself which ignores parameter)
#Reference dataspaces need to be listed before their associated master dataspace

dataSpacesForPermissions = \
		Reference||Master Data - Reference|RTech Admin, \
		CommonReferenceDataSpace|Reference|Common Reference|RTech Admin

# Whether to also apply data set permissions to children of the dataspace
dataSetPermissionsInChildDataSpaces = true

# Create specified datasets if they don't exist
createDataSets = true

#Dataspace | Dataset | Data Model XSD (optional)
#Reference datasets need to be listed before their associated master dataset
dataSetsForPermissions = \
		CommonReferenceDataSpace|CommonReferenceDataSet|onebx-mdm:/WEB-INF/ebx/schemas/CommonReferenceDataModel.xsd
			
#Artifacts to import/export
adminDataSetPermissions = false
directory = true
globalPermissions = false
views = true
tasks = true
perspectives = true
qualifyDataSetAndTableFileNames = true
historizationProfiles = true

#This section is used to identify the roles' prefixes or specific roles to be picked up and migrated from the directory. 
#Roles load as a replace (delete all roles with prefix on the server then load new roles)

#examples:
#	starts-with(./name, 'GP') \
#	or ends-with(./name, 'Tech Admin') \
#	or ./name='Workflow Administrator' \
#	or ./name='Permissions User' \
#	or ./name='Test User' \
#	or ./name='Service User' \
#	and not(starts-with(./name, 'GPBP'))\
#	and not(ends-with(./name, 'Something'))
tenantRolesPredicate = \
		starts-with(./name, 'onebx_')

#This section is used to identify the users' prefixes, roles containing users, or specific users to be picked up and migrated from the directory, assuming users are in roles above. 
#Users load as a replace (delete all users with prefix on the server then load new users)
#Test User should be commented out for UAT and PROD branches
usersRolesPredicate = \
		./role = 'PermissionsUser' \
		or ./role = 'TestUser'

#For perspectives, either option or both options can be used. Option #2 is preferred as it is simpler
#Option 1: Identifies the specific perspectives to include
#tenantPerspectives = \
#		InvistaPerspectives

#Option 2: Identifies the perspective prefix to include
tenantPerspectivesPrefix = \
         onebx_		
		
#Workflows are identified for export by their association to the module in the workflow configuration menu

#Master workflow | Sub-workflow 1 | Sub-workflow 2 | etc...
#Any workflow not listed will be published stand-alone (with no master)
#If a workflow is used both as a sub-workflow and as its own stand-alone workflow, then it should also be listed here with no sub-workflows 
#masterWorkflowModels = \
#		MasterWF|SubWF1|SubWF2|SubWF3

#Workflow models that can be imported and exported but we want to ignore when publishing.
#configuration workflow model is a built-in workflow model that is always ignored so doesn't need to be listed.
#workflowModelsToNotPublish = \
		
#Custom table views prefix
#To list specific views: tenantViewPublications = GPBPCreditDataEntryInbox
tenantViewPublicationsPrefix = onebx_

#Workflow message template range. This range is specific to the tenant. Do not change
tenantMessageTemplateRange = 1000-1999
			
addonAdix = false
addonDqid = false
addonHmfh = false
addonRpfl = false
addonMame = false
addonDpra = true
authorizedRole=Tech Admin

removeAdministratorRole = false
addonDamaDrivePathPrefix = ../DigitalAssets/
addonDamaTenantPrefix = [onebx_]
